export enum OrderStatus {
  PLACED = "PLACED",
  CONFIRMED = "CONFIRMED",
  IN_KITCHEN = "IN_KITCHEN",
  READY_FOR_PICKUP = "READY_FOR_PICKUP",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}
